#!/bin/bash

if [ -f '/etc/redhat-release' ]; then
	yum install -y epel-release
	yum install -y git
	yum install -y easy_install
	easy_install pip
	yum install -y yum-utils device-mapper-persistent-data lvm2
	yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
	yum install -y docker-ce
	systemctl start docker
	systemctl enable docker
	service docker start
	docker pull manageiq/manageiq:gaprindashvili-4
	docker run --privileged -d -p 8443:443 manageiq/manageiq:gaprindashvili-4
else
	apt-get update -y
	apt-get install apt-transport-https ca-certificates curl software-properties-common -y
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	apt-key fingerprint 0EBFCD88
	add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
	apt-get update -y
	apt-get install docker-ce -y
	service docker start
	docker pull manageiq/manageiq:gaprindashvili-4
	docker run --privileged -d -p 8443:443 manageiq/manageiq:gaprindashvili-4
fi
